### ISSUE TITLE
ArgumentError: marshal data too short

### ISSUE THREAD

**Issue by t0d0r** [aduffeck/uuid_it#3]
Hi again, i just switched to production and got this:

version of uuid_it (0.1.2)

ruby 1.9.2p290 , rails 3.0.10 and postgreSQL

```
irb(main):005:0> Car.new.uuid
ArgumentError: marshal data too short
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:118:in `load'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:118:in `read_state'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:170:in `block (2 levels) in create'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:168:in `open'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:168:in `block in create'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:139:in `chdir'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:139:in `create'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/uuid_it.rb:29:in `assign_uuid'
        from /usr/local/lib/ruby/gems/1.9.1/gems/uuid_it-0.1.2/lib/uuid_it.rb:22:in `uuid'
        from (irb):5
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.0.10/lib/rails/commands/console.rb:44:in `start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.0.10/lib/rails/commands/console.rb:8:in `start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-3.0.10/lib/rails/commands.rb:23:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

I can provide more information after a while.

**Comment by t0d0r** [comment]
I track down the problem to the empty file in Dir.tmpdir / ruby-uuid

I removed empty file and try from ruby 1.8.7 -> no problem, but from ruby 1.9.2 I got new error (which I think is related with empty file problem) 

Here is the new error:

```
ruby-1.9.2-p290 :001 > Car.new.uuid
Encoding::UndefinedConversionError: "\xA9" from ASCII-8BIT to UTF-8
    from /Users/t0d0r/.rvm/gems/ruby-1.9.2-p290/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:124:in `write'
    from /Users/t0d0r/.rvm/gems/ruby-1.9.2-p290/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb:124:in `write_state'
```

I dig in Google and found that in the new versions of ruby you must explicit set "b" flag when open binary files.

``` diff
--- uuid.rb 2011-09-28 21:48:11.000000000 +0300
+++ /Users/t0d0r/.rvm/gems/ruby-1.9.2-p290/gems/uuid_it-0.1.2/lib/ruby-uuid/uuid.rb 2011-09-28 21:20:51.000000000 +0300
@@ -159,13 +159,13 @@
                        node[0] |= 0x01 # multicast bit
                    end
                    k = rand 0x40000
-                   open STATE_FILE, 'w' do |fp|
+                   open STATE_FILE, 'wb' do |fp|
                        fp.flock IO::LOCK_EX
                        write_state fp, k, node
                        fp.chmod 0o777 # must be world writable
                    end
                end
-               open STATE_FILE, 'r+' do |fp|
+               open STATE_FILE, 'rb+' do |fp|
                    fp.flock IO::LOCK_EX
                    c, m = read_state fp
                    c = clock % 0x4000 if clock
```

**Comment by t0d0r** [comment]
almost same problem here: https://github.com/rails/rails/commit/f2c6f04f3b1b55c6516cb9376f109dcaa213db5d
